//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nickname { get; set; }
        public int power { get; set; }
        public System.DateTime createtime { get; set; }
        public Nullable<int> sex { get; set; }
        public string snumber { get; set; }
        public string faculty { get; set; }
    }
}
