//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string detail { get; set; }
        public Nullable<int> to_moment { get; set; }
        public string from_who { get; set; }
        public string to_who { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
