//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moment
    {
        public int id { get; set; }
        public string report_nickname { get; set; }
        public string detail { get; set; }
        public string picture_1 { get; set; }
        public string picture_2 { get; set; }
        public string picture_3 { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string title { get; set; }
    }
}
