//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Consulting_systemEntities : DbContext
    {
        public Consulting_systemEntities()
            : base("name=Consulting_systemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Text_1> Text_1 { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<like> like { get; set; }
        public virtual DbSet<moment> moment { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<TextResult> TextResult { get; set; }
    }
}
